import Picture from "./picture";

class QuestionClassError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "QuestionClassError";
  }
}

const fileNameToNameMap: Record<string, string> = {
  "ad.png": "Andorra",
  "ae.png": "United Arab Emirates",
  "af.png": "Afghanistan",
  "ag.png": "Antigua and Barbuda",
  "ai.png": "Anguilla",
  "al.png": "Albania",
  "am.png": "Armenia",
  "ao.png": "Angola",
  "aq.png": "Antarctica",
  "ar.png": "Argentina",
  "arab.png": "Arab League",
  "as.png": "American Samoa",
  "at.png": "Austria",
  "au.png": "Australia",
  "aw.png": "Aruba",
  "ax.png": "Åland Islands",
  "az.png": "Azerbaijan",
  "ba.png": "Bosnia and Herzegovina",
  "bb.png": "Barbados",
  "bd.png": "Bangladesh",
  "be.png": "Belgium",
  "bf.png": "Burkina Faso",
  "bg.png": "Bulgaria",
  "bh.png": "Bahrain",
  "bi.png": "Burundi",
  "bj.png": "Benin",
  "bl.png": "Saint Barthélemy",
  "bm.png": "Bermuda",
  "bn.png": "Brunei",
  "bo.png": "Bolivia",
  "bq.png": "Bonaire",
  "br.png": "Brazil",
  "bs.png": "Bahamas",
  "bt.png": "Bhutan",
  "bw.png": "Botswana",
  "by.png": "Belarus",
  "bz.png": "Belize",
  "ca.png": "Canada",
  "cc.png": "Cocos (Keeling) Islands",
  "cd.png": "Congo - Kinshasa",
  "cf.png": "Central African Republic",
  "cg.png": "Congo - Brazzaville",
  "ch.png": "Switzerland",
  "ci.png": "Côte d’Ivoire",
  "ck.png": "Cook Islands",
  "cl.png": "Chile",
  "cm.png": "Cameroon",
  "cn.png": "China",
  "co.png": "Colombia",
  "cp.png": "Clipperton Island",
  "cr.png": "Costa Rica",
  "cu.png": "Cuba",
  "cv.png": "Cape Verde",
  "cw.png": "Curaçao",
  "cx.png": "Christmas Island",
  "cy.png": "Cyprus",
  "cz.png": "Czech Republic",
  "de.png": "Germany",
  "dg.png": "Diego Garcia",
  "dj.png": "Djibouti",
  "dk.png": "Denmark",
  "dm.png": "Dominica",
  "do.png": "Dominican Republic",
  "dz.png": "Algeria",
  "eac.png": "East African Community",
  "ec.png": "Ecuador",
  "ee.png": "Estonia",
  "eg.png": "Egypt",
  "eh.png": "Western Sahara",
  "er.png": "Eritrea",
  "es-ct.png": "Catalonia",
  "es-ga.png": "Galicia",
  "es-pv.png": "Basque Country",
  "es.png": "Spain",
  "et.png": "Ethiopia",
  "eu.png": "European Union",
  "fi.png": "Finland",
  "fj.png": "Fiji",
  "fk.png": "Falkland Islands",
  "fm.png": "Micronesia",
  "fo.png": "Faroe Islands",
  "fr.png": "France",
  "ga.png": "Gabon",
  "gb-eng.png": "England",
  "gb-nir.png": "Northern Ireland",
  "gb-sct.png": "Scotland",
  "gb-wls.png": "Wales",
  "gb.png": "United Kingdom",
  "gd.png": "Grenada",
  "ge.png": "Georgia",
  "gf.png": "French Guiana",
  "gg.png": "Guernsey",
  "gh.png": "Ghana",
  "gi.png": "Gibraltar",
  "gl.png": "Greenland",
  "gm.png": "Gambia",
  "gn.png": "Guinea",
  "gp.png": "Guadeloupe",
  "gq.png": "Equatorial Guinea",
  "gr.png": "Greece",
  "gs.png": "South Georgia and South Sandwich Islands",
  "gt.png": "Guatemala",
  "gu.png": "Guam",
  "gw.png": "Guinea-Bissau",
  "gy.png": "Guyana",
  "hk.png": "Hong Kong",
  "hm.png": "Heard Island and McDonald Islands",
  "hn.png": "Honduras",
  "hr.png": "Croatia",
  "ht.png": "Haiti",
  "hu.png": "Hungary",
  "ic.png": "Canary Islands",
  "id.png": "Indonesia",
  "ie.png": "Ireland",
  "il.png": "Israel",
  "im.png": "Isle of Man",
  "in.png": "India",
  "io.png": "British Indian Ocean Territory",
  "iq.png": "Iraq",
  "ir.png": "Iran",
  "is.png": "Iceland",
  "it.png": "Italy",
  "je.png": "Jersey",
  "jm.png": "Jamaica",
  "jo.png": "Jordan",
  "jp.png": "Japan",
  "ke.png": "Kenya",
  "kg.png": "Kyrgyzstan",
  "kh.png": "Cambodia",
  "ki.png": "Kiribati",
  "km.png": "Comoros",
  "kn.png": "Saint Kitts and Nevis",
  "kp.png": "North Korea",
  "kr.png": "South Korea",
  "kw.png": "Kuwait",
  "ky.png": "Cayman Islands",
  "kz.png": "Kazakhstan",
  "la.png": "Laos",
  "lb.png": "Lebanon",
  "lc.png": "Saint Lucia",
  "li.png": "Liechtenstein",
  "lk.png": "Sri Lanka",
  "lr.png": "Liberia",
  "ls.png": "Lesotho",
  "lt.png": "Lithuania",
  "lu.png": "Luxembourg",
  "lv.png": "Latvia",
  "ly.png": "Libya",
  "ma.png": "Morocco",
  "mc.png": "Monaco",
  "md.png": "Moldova",
  "me.png": "Montenegro",
  "mf.png": "Saint Martin",
  "mg.png": "Madagascar",
  "mh.png": "Marshall Islands",
  "mk.png": "North Macedonia",
  "ml.png": "Mali",
  "mm.png": "Myanmar (Burma)",
  "mn.png": "Mongolia",
  "mo.png": "Macao",
  "mp.png": "Northern Mariana Islands",
  "mq.png": "Martinique",
  "mr.png": "Mauritania",
  "ms.png": "Montserrat",
  "mt.png": "Malta",
  "mu.png": "Mauritius",
  "mv.png": "Maldives",
  "mw.png": "Malawi",
  "mx.png": "Mexico",
  "my.png": "Malaysia",
  "mz.png": "Mozambique",
  "na.png": "Namibia",
  "nc.png": "New Caledonia",
  "ne.png": "Niger",
  "nf.png": "Norfolk Island",
  "ng.png": "Nigeria",
  "ni.png": "Nicaragua",
  "nl.png": "Netherlands",
  "no.png": "Norway",
  "np.png": "Nepal",
  "nr.png": "Nauru",
  "nu.png": "Niue",
  "nz.png": "New Zealand",
  "om.png": "Oman",
  "pa.png": "Panama",
  "pc.png": "Pacific Community",
  "pe.png": "Peru",
  "pf.png": "French Polynesia",
  "pg.png": "Papua New Guinea",
  "ph.png": "Philippines",
  "pk.png": "Pakistan",
  "pl.png": "Poland",
  "pm.png": "Saint Pierre and Miquelon",
  "pn.png": "Pitcairn Islands",
  "pr.png": "Puerto Rico",
  "ps.png": "Palestine",
  "pt.png": "Portugal",
  "pw.png": "Palau",
  "py.png": "Paraguay",
  "qa.png": "Qatar",
  "re.png": "Réunion",
  "ro.png": "Romania",
  "rs.png": "Serbia",
  "ru.png": "Russia",
  "rw.png": "Rwanda",
  "sa.png": "Saudi Arabia",
  "sb.png": "Solomon Islands",
  "sc.png": "Seychelles",
  "sd.png": "Sudan",
  "se.png": "Sweden",
  "sg.png": "Singapore",
  "sh-ac.png": "Ascension Island",
  "sh-hl.png": "Saint Helena",
  "sh-ta.png": "Tristan da Cunha",
  "sh.png": "Saint Helena",
  "si.png": "Slovenia",
  "sj.png": "Svalbard and Jan Mayen",
  "sk.png": "Slovakia",
  "sl.png": "Sierra Leone",
  "sm.png": "San Marino",
  "sn.png": "Senegal",
  "so.png": "Somalia",
  "sr.png": "Suriname",
  "ss.png": "South Sudan",
  "st.png": "São Tomé and Príncipe",
  "sv.png": "El Salvador",
  "sx.png": "Sint Maarten",
  "sy.png": "Syria",
  "sz.png": "Eswatini",
  "tc.png": "Turks and Caicos Islands",
  "td.png": "Chad",
  "tf.png": "French Southern Territories",
  "tg.png": "Togo",
  "th.png": "Thailand",
  "tj.png": "Tajikistan",
  "tk.png": "Tokelau",
  "tl.png": "Timor-Leste",
  "tm.png": "Turkmenistan",
  "tn.png": "Tunisia",
  "to.png": "Tonga",
  "tr.png": "Turkey",
  "tt.png": "Trinidad and Tobago",
  "tv.png": "Tuvalu",
  "tw.png": "Taiwan",
  "tz.png": "Tanzania",
  "ua.png": "Ukraine",
  "ug.png": "Uganda",
  "um.png": "U.S. Outlying Islands",
  "un.png": "United Nations",
  "us.png": "United States",
  "uy.png": "Uruguay",
  "uz.png": "Uzbekistan",
  "va.png": "Vatican City",
  "vc.png": "Saint Vincent and the Grenadines",
  "ve.png": "Venezuela",
  "vg.png": "British Virgin Islands",
  "vi.png": "U.S. Virgin Islands",
  "vn.png": "Vietnam",
  "vu.png": "Vanuatu",
  "wf.png": "Wallis and Futuna",
  "ws.png": "Samoa",
  "xk.png": "Kosovo",
  "xx.png": "Unknown Region",
  "ye.png": "Yemen",
  "yt.png": "Mayotte",
  "za.png": "South Africa",
  "zm.png": "Zambia",
  "zw.png": "Zimbabwe",
};

export default class Question {
  private readonly pictures: Picture[] = [];
  private readonly correctPictureIndex: number;
  private readonly questionString: string;

  constructor(pictures: Picture[], correctPictureIndex: number) {
    if (pictures.length !== 4 && correctPictureIndex !== -1) {
      throw new QuestionClassError("doesn't have 4 pictures");
    }
    if (correctPictureIndex < -1 || correctPictureIndex > 3) {
      throw new QuestionClassError("correctPictureIndex out of range");
    }
    this.correctPictureIndex = correctPictureIndex;
    this.pictures = pictures;

    if (correctPictureIndex === -1) {
      this.questionString = ``;
    } else {
      this.questionString = `Which picture shows the flag of ${fileNameToNameMap[pictures[correctPictureIndex].getName()]}`;
    }
  }

  public getPictures(): Picture[] {
    return this.pictures;
  }

  public getQuestionString(): string {
    return this.questionString;
  }

  public isCorrect(index: number): boolean {
    return index === this.correctPictureIndex;
  }
}
